import { GoogleSpreadsheet } from "google-spreadsheet";

const TRACKER_SHEET_ID = "1PrfPAxLEsQdKUCwHCLZ7gMBiv10CY1v3gRVx5Gh1QHY";

export default async function initialize(): Promise<GoogleSpreadsheet> {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet(TRACKER_SHEET_ID);

  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL as string,
    private_key: process.env.GOOGLE_PRIVATE_KEY as string,
  });

  return doc;
}
